version: "3"
services:
    db:
        ports:
            - "1433:1433"
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "root@111"
            ACCEPT_EULA: "Y"
            PATH: "/opt/mssql/bin:/opt/mssql-tools/bin:$PATH"